### PR TITLE
Update user endpoint

### PR DESCRIPTION
**Pull request by Logan1x**

### CODE REVIEW

**Comment by Logan1x** [comment]
For issue #43

**Comment by Logan1x** [comment]
@austitech Please review it

**Comment by iameo** [comment]
In swagger file:

OperationId: "endpoints.user.**userupdate**.update"
not "endpoints.user.**user_update**.update"

Your file is userupdate.py.

**Comment by Logan1x** [comment]
Sorry for the inconveniences, it's fixed now @iameo Thanks 🤙

**Comment by Logan1x** [comment]
Any update on this? @iameo

**Pull request merged**
