### PR TITLE
Added update transaction endpoint

### PR DESCRIPTION
**Pull request by Clashkid155**
Check telegram for update endpoint in action. Finally done. 
[Telegram link](https://t.me/c/1202421465/1340)

### CODE REVIEW

**Comment by iameo** [comment]
@Clashkid155, you really shouldn’t be updating created_at and updated_at. You’re typically saying that a user should be able to update when their transaction was created. That’s a slippery slope.

**Comment by Clashkid155** [comment]
@iameo Read my code again or watch the video.

**Comment by iameo** [comment]
Pre-save signal handles updated_at for when a change is made to the Transaction model. Assigning it to datetime.now() is redundant as that is already taken care of, internally. 

You may choose to leave it like that. It’ll be eventually commented out when there’s a code refactor, if the pre_save signal is kept in the model. ✊🏽

**Comment by Clashkid155** [comment]
😐 @iameo presave doesn't update updated_at.

**Pull request merged**
